### PR TITLE
Command Line Runner API changes

### LINKED ISSUE #298: Compilation warnings are treated as errors in `TestsCompiler`
**Describe the bug**
`TestsCompiler` does not distinguish between warnings and errors because the errors are classified by the fact of having any output from the underlying compiler. It makes warnings & errors indistinguishable since both are text messages.

We need to check the underlying compiler return code to understand whether there was a compilation error.

**To Reproduce**
1. Make LLM generate compilable unit tests that produce a warning during compilation (idk how to cause it intentionally; writing a custom prompt asking for a warning may help).
2. The feedback cycle iteration will complain that an error occurred while compiling the test suite, although the test suite is compilable, and the warning was mistakenly treated as an error.

**Expected behavior**
Warnings should not be treated as errors if the test suite is compilable. We need to reimplement the `TestsCompiler` so that it checks for the underlying compiler utility's **return code**.

**Additional context**
See the `TestsCompiler` implementation.

### PR DESCRIPTION
**Pull request by Hello-zoka**
# Description of changes made
`CommandLineRunner` wasn't returning the exit code of the execution, which made Errors/Warnings/stdout indistinguishable. This PR fixes it.  **Please**, make sure to test it as well since it changes the core logic. 

Closes #298 and #361

# Release

We probably don't want to include it in upcoming major releases to make sure everything works smoothly. 

# Notes for merging

Conflicts with PR #376

- [x] I have checked that I am merging into the correct branch

### CODE REVIEW

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt [hunk 1]
```diff
@@ -9,13 +9,13 @@ class CommandLineRunner {
...
-         * Executes a command line process and returns the output as a string.
+         * Executes a command line process
          *
          * @param cmd The command line arguments as an ArrayList of strings.
-         * @return The output of the command line process as a string.
+         * @return A pair containing exit value and a string message containing execution results
          */
-        fun run(cmd: ArrayList<String>): String {
-            var errorMessage = ""
+        fun run(cmd: ArrayList<String>): Pair<Int, String> {
```
Comment (Vladislav0Art) [inline core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt:17]: Instead of returning a pair, return a data class. 

Now, as a reviewer I cannot understand what `first` and what `second` actually are. 

In practice, a data class should always be preferred over a pair, especially in our case where a lot of components depend on it.

File: src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt [hunk 2]
```diff
@@ -140,7 +140,7 @@ class TestProcessor(
 
         CommandLineRunner.run(command as ArrayList<String>)
 
-        return testExecutionError
+        return if (testExecutionResult.first == 0) "" else testExecutionResult.second
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt:143]: Once you replace a pair with a data class, I recommend creating a method `succeeded/executionSucceeded(): Bool` and call it here instead of `== 0`. 

We do not want a `TestProcessor` to manually check the success condition; it is not his responsibility to know cli command-related concepts.

File: src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/generation/EvoSuiteProcessManager.kt [hunk 3]
```diff
@@ -84,7 +84,7 @@ class EvoSuiteProcessManager(
             if (ToolUtils.isProcessStopped(errorMonitor, indicator)) return null
 
             val regex = Regex("version \"(.*?)\"")
-            val version = regex.find(CommandLineRunner.run(arrayListOf(evoSuiteSettingsState.javaPath, "-version")))
+            val version = regex.find(CommandLineRunner.run(arrayListOf(evoSuiteSettingsState.javaPath, "-version")).second)
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/generation/EvoSuiteProcessManager.kt:87]: Almost unreadable.

I recommend moving the following part into a named variable:
```kotlin
CommandLineRunner.run(arrayListOf(evoSuiteSettingsState.javaPath, "-version"))
```

**Review by Vladislav0Art — CHANGES_REQUESTED** [review]
I skimmed through the implementation (did not test it; did not look at every file). I will make a more through review tomorrow/after the release.

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt (hunk 1 above)
Comment (Hello-zoka) [reply core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt:17]: I've done it to match the current style of the `compileCode` method. I do find it kinda ugly, so I will refactor both signatures

**Comment by pderakhshanfar** [comment]
@Hello-zoka I agree with Vladislav's comments, please:
1- fix his comments
2- Resolve merging issues

Then, we will check the code again. Thanks

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt (hunk 1 above)
Comment (Vladislav0Art) [reply core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt:17]: >  I will refactor both signatures

Yeah, that is even better. Thanks!

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt [hunk 4]
```diff
@@ -270,7 +270,9 @@ class LLMWithFeedbackCycle(
                 onWarningCallback?.invoke(WarningType.COMPILATION_ERROR_OCCURRED)
 
                 nextPromptMessage =
-                    "I cannot compile the tests that you provided. The error is:\n${testSuiteCompilationResult.second}\n Fix this issue in the provided tests.\nGenerate public classes and public methods. Response only a code with tests between ```, do not provide any other text."
+                    "I cannot compile the tests that you provided. The error is:\n${testSuiteCompilationResult.executionMessage}" +
+                            "\n Fix this issue in the provided tests.\nGenerate public classes and public methods. Response only a code with tests between ```," +
+                            " do not provide any other text."
```
Comment (Vladislav0Art) [inline core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt:275]: You can do:
````kotlin
nextPromptMessage = """
  I cannot compile the tests that you provided. The error is:
  ```
  ${testSuiteCompilationResult.executionMessage}
  ```

   Fix this issue in the provided tests.\nGenerate public classes and public methods. Response only a code with tests between ```, do not provide any other text.
""".trimIndent()
````

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt [hunk 5]
```diff
@@ -9,13 +10,13 @@ class CommandLineRunner {
         protected val log = KotlinLogging.logger {}
 
         /**
-         * Executes a command line process and returns the output as a string.
+         * Executes a command line process
          *
          * @param cmd The command line arguments as an ArrayList of strings.
-         * @return The output of the command line process as a string.
+         * @return A pair containing exit value and a string message containing execution results
```
Comment (Vladislav0Art) [inline core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt:16]: 1. `exit value` -> `exit code [of the executed process]`
2. `message containing execution results` -> `message containing stdout and stderr of the executed process`.

File: core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt [hunk 6]
```diff
@@ -32,17 +33,15 @@ class CommandLineRunner {
                     .redirectErrorStream(true)
                     .start()
             }
-
             val reader = BufferedReader(InputStreamReader(process.inputStream))
             var line: String?
 
             while (reader.readLine().also { line = it } != null) {
-                errorMessage += line
+                executionMsg += line
```
Comment (Vladislav0Art) [inline core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/CommandLineRunner.kt:40]: By the way, this implementation does not respect line breaks. Therefore, if you noticed, we have error stack traces in a single line.

We need:
```kotlin
val sep = System.lineSeparator();
while (..) {
  executionMsg += "$line$sep"
}
```

File: src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt [hunk 7]
```diff
@@ -110,7 +110,7 @@ class TestProcessor(
             ),
         )
 
-        log.info("Test execution error message: $testExecutionError")
+        log.info("Test execution message: ${testExecutionResult.executionMessage}")
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt:113]: Print the exit code also, for this matter.

File: src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt [hunk 8]
```diff
@@ -140,7 +140,7 @@ class TestProcessor(
 
         CommandLineRunner.run(command as ArrayList<String>)
 
-        return testExecutionError
+        return if (testExecutionResult.isSuccessful()) "" else testExecutionResult.executionMessage
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt:143]: It is advisable to change the API of this `TestProcessor`'s method to return `testExecutionResult`. I guess it requires a lot of refactoring; therefore, it is not for this PR.

Leave a TODO to change the method's return contract.

File: src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/generation/EvoSuiteProcessManager.kt [hunk 9]
```diff
@@ -84,7 +84,8 @@ class EvoSuiteProcessManager(
             if (ToolUtils.isProcessStopped(errorMonitor, indicator)) return null
 
             val regex = Regex("version \"(.*?)\"")
-            val version = regex.find(CommandLineRunner.run(arrayListOf(evoSuiteSettingsState.javaPath, "-version")))
+            val versionCommandResult = CommandLineRunner.run(arrayListOf(evoSuiteSettingsState.javaPath, "-version"))
+            val version = regex.find(versionCommandResult.executionMessage)
```
Comment (Vladislav0Art) [inline src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/generation/EvoSuiteProcessManager.kt:88]: How about logging the `versionCommandResult`'s exit code and message?
it'll become easier to trace issues with the set `java` filepath when using EvoSuite.

**Review by Vladislav0Art — APPROVED** [review]
I left some recommendations and suggestions. Nothing critical, although I advise you to consider them.

👍

**Comment by Hello-zoka** [comment]
Ready to merge, if there are no problems with @pderakhshanfar @arksap2002

**Review by pderakhshanfar — APPROVED** [review]
